// Code generated by entc, DO NOT EDIT.

package storage

import (
	"context"
	"errors"
	"fmt"
	"math"
	"news/internal/storage/articlepost"
	"news/internal/storage/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticlePostQuery is the builder for querying ArticlePost entities.
type ArticlePostQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ArticlePost
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ArticlePostQuery builder.
func (apq *ArticlePostQuery) Where(ps ...predicate.ArticlePost) *ArticlePostQuery {
	apq.predicates = append(apq.predicates, ps...)
	return apq
}

// Limit adds a limit step to the query.
func (apq *ArticlePostQuery) Limit(limit int) *ArticlePostQuery {
	apq.limit = &limit
	return apq
}

// Offset adds an offset step to the query.
func (apq *ArticlePostQuery) Offset(offset int) *ArticlePostQuery {
	apq.offset = &offset
	return apq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (apq *ArticlePostQuery) Unique(unique bool) *ArticlePostQuery {
	apq.unique = &unique
	return apq
}

// Order adds an order step to the query.
func (apq *ArticlePostQuery) Order(o ...OrderFunc) *ArticlePostQuery {
	apq.order = append(apq.order, o...)
	return apq
}

// First returns the first ArticlePost entity from the query.
// Returns a *NotFoundError when no ArticlePost was found.
func (apq *ArticlePostQuery) First(ctx context.Context) (*ArticlePost, error) {
	nodes, err := apq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{articlepost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (apq *ArticlePostQuery) FirstX(ctx context.Context) *ArticlePost {
	node, err := apq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ArticlePost ID from the query.
// Returns a *NotFoundError when no ArticlePost ID was found.
func (apq *ArticlePostQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = apq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{articlepost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (apq *ArticlePostQuery) FirstIDX(ctx context.Context) int {
	id, err := apq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ArticlePost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ArticlePost entity is found.
// Returns a *NotFoundError when no ArticlePost entities are found.
func (apq *ArticlePostQuery) Only(ctx context.Context) (*ArticlePost, error) {
	nodes, err := apq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{articlepost.Label}
	default:
		return nil, &NotSingularError{articlepost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (apq *ArticlePostQuery) OnlyX(ctx context.Context) *ArticlePost {
	node, err := apq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ArticlePost ID in the query.
// Returns a *NotSingularError when more than one ArticlePost ID is found.
// Returns a *NotFoundError when no entities are found.
func (apq *ArticlePostQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = apq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = &NotSingularError{articlepost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (apq *ArticlePostQuery) OnlyIDX(ctx context.Context) int {
	id, err := apq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ArticlePosts.
func (apq *ArticlePostQuery) All(ctx context.Context) ([]*ArticlePost, error) {
	if err := apq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return apq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (apq *ArticlePostQuery) AllX(ctx context.Context) []*ArticlePost {
	nodes, err := apq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ArticlePost IDs.
func (apq *ArticlePostQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := apq.Select(articlepost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (apq *ArticlePostQuery) IDsX(ctx context.Context) []int {
	ids, err := apq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (apq *ArticlePostQuery) Count(ctx context.Context) (int, error) {
	if err := apq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return apq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (apq *ArticlePostQuery) CountX(ctx context.Context) int {
	count, err := apq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (apq *ArticlePostQuery) Exist(ctx context.Context) (bool, error) {
	if err := apq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return apq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (apq *ArticlePostQuery) ExistX(ctx context.Context) bool {
	exist, err := apq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ArticlePostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (apq *ArticlePostQuery) Clone() *ArticlePostQuery {
	if apq == nil {
		return nil
	}
	return &ArticlePostQuery{
		config:     apq.config,
		limit:      apq.limit,
		offset:     apq.offset,
		order:      append([]OrderFunc{}, apq.order...),
		predicates: append([]predicate.ArticlePost{}, apq.predicates...),
		// clone intermediate query.
		sql:    apq.sql.Clone(),
		path:   apq.path,
		unique: apq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status bool `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ArticlePost.Query().
//		GroupBy(articlepost.FieldStatus).
//		Aggregate(storage.Count()).
//		Scan(ctx, &v)
//
func (apq *ArticlePostQuery) GroupBy(field string, fields ...string) *ArticlePostGroupBy {
	group := &ArticlePostGroupBy{config: apq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := apq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return apq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status bool `json:"status,omitempty"`
//	}
//
//	client.ArticlePost.Query().
//		Select(articlepost.FieldStatus).
//		Scan(ctx, &v)
//
func (apq *ArticlePostQuery) Select(fields ...string) *ArticlePostSelect {
	apq.fields = append(apq.fields, fields...)
	return &ArticlePostSelect{ArticlePostQuery: apq}
}

func (apq *ArticlePostQuery) prepareQuery(ctx context.Context) error {
	for _, f := range apq.fields {
		if !articlepost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("storage: invalid field %q for query", f)}
		}
	}
	if apq.path != nil {
		prev, err := apq.path(ctx)
		if err != nil {
			return err
		}
		apq.sql = prev
	}
	return nil
}

func (apq *ArticlePostQuery) sqlAll(ctx context.Context) ([]*ArticlePost, error) {
	var (
		nodes = []*ArticlePost{}
		_spec = apq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ArticlePost{config: apq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("storage: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, apq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (apq *ArticlePostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := apq.querySpec()
	_spec.Node.Columns = apq.fields
	if len(apq.fields) > 0 {
		_spec.Unique = apq.unique != nil && *apq.unique
	}
	return sqlgraph.CountNodes(ctx, apq.driver, _spec)
}

func (apq *ArticlePostQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := apq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("storage: check existence: %w", err)
	}
	return n > 0, nil
}

func (apq *ArticlePostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   articlepost.Table,
			Columns: articlepost.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: articlepost.FieldID,
			},
		},
		From:   apq.sql,
		Unique: true,
	}
	if unique := apq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := apq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, articlepost.FieldID)
		for i := range fields {
			if fields[i] != articlepost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := apq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := apq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := apq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := apq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (apq *ArticlePostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(apq.driver.Dialect())
	t1 := builder.Table(articlepost.Table)
	columns := apq.fields
	if len(columns) == 0 {
		columns = articlepost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if apq.sql != nil {
		selector = apq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if apq.unique != nil && *apq.unique {
		selector.Distinct()
	}
	for _, p := range apq.predicates {
		p(selector)
	}
	for _, p := range apq.order {
		p(selector)
	}
	if offset := apq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := apq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ArticlePostGroupBy is the group-by builder for ArticlePost entities.
type ArticlePostGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (apgb *ArticlePostGroupBy) Aggregate(fns ...AggregateFunc) *ArticlePostGroupBy {
	apgb.fns = append(apgb.fns, fns...)
	return apgb
}

// Scan applies the group-by query and scans the result into the given value.
func (apgb *ArticlePostGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := apgb.path(ctx)
	if err != nil {
		return err
	}
	apgb.sql = query
	return apgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := apgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (apgb *ArticlePostGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(apgb.fields) > 1 {
		return nil, errors.New("storage: ArticlePostGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := apgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) StringsX(ctx context.Context) []string {
	v, err := apgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (apgb *ArticlePostGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = apgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = fmt.Errorf("storage: ArticlePostGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) StringX(ctx context.Context) string {
	v, err := apgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (apgb *ArticlePostGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(apgb.fields) > 1 {
		return nil, errors.New("storage: ArticlePostGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := apgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) IntsX(ctx context.Context) []int {
	v, err := apgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (apgb *ArticlePostGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = apgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = fmt.Errorf("storage: ArticlePostGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) IntX(ctx context.Context) int {
	v, err := apgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (apgb *ArticlePostGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(apgb.fields) > 1 {
		return nil, errors.New("storage: ArticlePostGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := apgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := apgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (apgb *ArticlePostGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = apgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = fmt.Errorf("storage: ArticlePostGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) Float64X(ctx context.Context) float64 {
	v, err := apgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (apgb *ArticlePostGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(apgb.fields) > 1 {
		return nil, errors.New("storage: ArticlePostGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := apgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := apgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (apgb *ArticlePostGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = apgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = fmt.Errorf("storage: ArticlePostGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (apgb *ArticlePostGroupBy) BoolX(ctx context.Context) bool {
	v, err := apgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (apgb *ArticlePostGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range apgb.fields {
		if !articlepost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := apgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := apgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (apgb *ArticlePostGroupBy) sqlQuery() *sql.Selector {
	selector := apgb.sql.Select()
	aggregation := make([]string, 0, len(apgb.fns))
	for _, fn := range apgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(apgb.fields)+len(apgb.fns))
		for _, f := range apgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(apgb.fields...)...)
}

// ArticlePostSelect is the builder for selecting fields of ArticlePost entities.
type ArticlePostSelect struct {
	*ArticlePostQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aps *ArticlePostSelect) Scan(ctx context.Context, v interface{}) error {
	if err := aps.prepareQuery(ctx); err != nil {
		return err
	}
	aps.sql = aps.ArticlePostQuery.sqlQuery(ctx)
	return aps.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aps *ArticlePostSelect) ScanX(ctx context.Context, v interface{}) {
	if err := aps.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (aps *ArticlePostSelect) Strings(ctx context.Context) ([]string, error) {
	if len(aps.fields) > 1 {
		return nil, errors.New("storage: ArticlePostSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := aps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aps *ArticlePostSelect) StringsX(ctx context.Context) []string {
	v, err := aps.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (aps *ArticlePostSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aps.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = fmt.Errorf("storage: ArticlePostSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aps *ArticlePostSelect) StringX(ctx context.Context) string {
	v, err := aps.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (aps *ArticlePostSelect) Ints(ctx context.Context) ([]int, error) {
	if len(aps.fields) > 1 {
		return nil, errors.New("storage: ArticlePostSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := aps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aps *ArticlePostSelect) IntsX(ctx context.Context) []int {
	v, err := aps.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (aps *ArticlePostSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aps.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = fmt.Errorf("storage: ArticlePostSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aps *ArticlePostSelect) IntX(ctx context.Context) int {
	v, err := aps.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (aps *ArticlePostSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(aps.fields) > 1 {
		return nil, errors.New("storage: ArticlePostSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := aps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aps *ArticlePostSelect) Float64sX(ctx context.Context) []float64 {
	v, err := aps.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (aps *ArticlePostSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aps.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = fmt.Errorf("storage: ArticlePostSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aps *ArticlePostSelect) Float64X(ctx context.Context) float64 {
	v, err := aps.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (aps *ArticlePostSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(aps.fields) > 1 {
		return nil, errors.New("storage: ArticlePostSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := aps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aps *ArticlePostSelect) BoolsX(ctx context.Context) []bool {
	v, err := aps.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (aps *ArticlePostSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aps.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{articlepost.Label}
	default:
		err = fmt.Errorf("storage: ArticlePostSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aps *ArticlePostSelect) BoolX(ctx context.Context) bool {
	v, err := aps.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aps *ArticlePostSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aps.sql.Query()
	if err := aps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
