// Code generated by entc, DO NOT EDIT.

package storage

import (
	"context"
	"fmt"
	"news/internal/storage/mediapost"
	"news/internal/storage/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaPostDelete is the builder for deleting a MediaPost entity.
type MediaPostDelete struct {
	config
	hooks    []Hook
	mutation *MediaPostMutation
}

// Where appends a list predicates to the MediaPostDelete builder.
func (mpd *MediaPostDelete) Where(ps ...predicate.MediaPost) *MediaPostDelete {
	mpd.mutation.Where(ps...)
	return mpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mpd *MediaPostDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mpd.hooks) == 0 {
		affected, err = mpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MediaPostMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mpd.mutation = mutation
			affected, err = mpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mpd.hooks) - 1; i >= 0; i-- {
			if mpd.hooks[i] == nil {
				return 0, fmt.Errorf("storage: uninitialized hook (forgotten import storage/runtime?)")
			}
			mut = mpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpd *MediaPostDelete) ExecX(ctx context.Context) int {
	n, err := mpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mpd *MediaPostDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: mediapost.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mediapost.FieldID,
			},
		},
	}
	if ps := mpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mpd.driver, _spec)
}

// MediaPostDeleteOne is the builder for deleting a single MediaPost entity.
type MediaPostDeleteOne struct {
	mpd *MediaPostDelete
}

// Exec executes the deletion query.
func (mpdo *MediaPostDeleteOne) Exec(ctx context.Context) error {
	n, err := mpdo.mpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediapost.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mpdo *MediaPostDeleteOne) ExecX(ctx context.Context) {
	mpdo.mpd.ExecX(ctx)
}
