// Code generated by entc, DO NOT EDIT.

package storage

import (
	"context"
	"errors"
	"fmt"
	"math"
	"news/internal/storage/mediapost"
	"news/internal/storage/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaPostQuery is the builder for querying MediaPost entities.
type MediaPostQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MediaPost
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MediaPostQuery builder.
func (mpq *MediaPostQuery) Where(ps ...predicate.MediaPost) *MediaPostQuery {
	mpq.predicates = append(mpq.predicates, ps...)
	return mpq
}

// Limit adds a limit step to the query.
func (mpq *MediaPostQuery) Limit(limit int) *MediaPostQuery {
	mpq.limit = &limit
	return mpq
}

// Offset adds an offset step to the query.
func (mpq *MediaPostQuery) Offset(offset int) *MediaPostQuery {
	mpq.offset = &offset
	return mpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mpq *MediaPostQuery) Unique(unique bool) *MediaPostQuery {
	mpq.unique = &unique
	return mpq
}

// Order adds an order step to the query.
func (mpq *MediaPostQuery) Order(o ...OrderFunc) *MediaPostQuery {
	mpq.order = append(mpq.order, o...)
	return mpq
}

// First returns the first MediaPost entity from the query.
// Returns a *NotFoundError when no MediaPost was found.
func (mpq *MediaPostQuery) First(ctx context.Context) (*MediaPost, error) {
	nodes, err := mpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mediapost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mpq *MediaPostQuery) FirstX(ctx context.Context) *MediaPost {
	node, err := mpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MediaPost ID from the query.
// Returns a *NotFoundError when no MediaPost ID was found.
func (mpq *MediaPostQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mediapost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mpq *MediaPostQuery) FirstIDX(ctx context.Context) int {
	id, err := mpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MediaPost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MediaPost entity is found.
// Returns a *NotFoundError when no MediaPost entities are found.
func (mpq *MediaPostQuery) Only(ctx context.Context) (*MediaPost, error) {
	nodes, err := mpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mediapost.Label}
	default:
		return nil, &NotSingularError{mediapost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mpq *MediaPostQuery) OnlyX(ctx context.Context) *MediaPost {
	node, err := mpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MediaPost ID in the query.
// Returns a *NotSingularError when more than one MediaPost ID is found.
// Returns a *NotFoundError when no entities are found.
func (mpq *MediaPostQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = &NotSingularError{mediapost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mpq *MediaPostQuery) OnlyIDX(ctx context.Context) int {
	id, err := mpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MediaPosts.
func (mpq *MediaPostQuery) All(ctx context.Context) ([]*MediaPost, error) {
	if err := mpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mpq *MediaPostQuery) AllX(ctx context.Context) []*MediaPost {
	nodes, err := mpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MediaPost IDs.
func (mpq *MediaPostQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := mpq.Select(mediapost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mpq *MediaPostQuery) IDsX(ctx context.Context) []int {
	ids, err := mpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mpq *MediaPostQuery) Count(ctx context.Context) (int, error) {
	if err := mpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mpq *MediaPostQuery) CountX(ctx context.Context) int {
	count, err := mpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mpq *MediaPostQuery) Exist(ctx context.Context) (bool, error) {
	if err := mpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mpq *MediaPostQuery) ExistX(ctx context.Context) bool {
	exist, err := mpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MediaPostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mpq *MediaPostQuery) Clone() *MediaPostQuery {
	if mpq == nil {
		return nil
	}
	return &MediaPostQuery{
		config:     mpq.config,
		limit:      mpq.limit,
		offset:     mpq.offset,
		order:      append([]OrderFunc{}, mpq.order...),
		predicates: append([]predicate.MediaPost{}, mpq.predicates...),
		// clone intermediate query.
		sql:    mpq.sql.Clone(),
		path:   mpq.path,
		unique: mpq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status bool `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MediaPost.Query().
//		GroupBy(mediapost.FieldStatus).
//		Aggregate(storage.Count()).
//		Scan(ctx, &v)
//
func (mpq *MediaPostQuery) GroupBy(field string, fields ...string) *MediaPostGroupBy {
	group := &MediaPostGroupBy{config: mpq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mpq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status bool `json:"status,omitempty"`
//	}
//
//	client.MediaPost.Query().
//		Select(mediapost.FieldStatus).
//		Scan(ctx, &v)
//
func (mpq *MediaPostQuery) Select(fields ...string) *MediaPostSelect {
	mpq.fields = append(mpq.fields, fields...)
	return &MediaPostSelect{MediaPostQuery: mpq}
}

func (mpq *MediaPostQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mpq.fields {
		if !mediapost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("storage: invalid field %q for query", f)}
		}
	}
	if mpq.path != nil {
		prev, err := mpq.path(ctx)
		if err != nil {
			return err
		}
		mpq.sql = prev
	}
	return nil
}

func (mpq *MediaPostQuery) sqlAll(ctx context.Context) ([]*MediaPost, error) {
	var (
		nodes = []*MediaPost{}
		_spec = mpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &MediaPost{config: mpq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("storage: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, mpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mpq *MediaPostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mpq.querySpec()
	_spec.Node.Columns = mpq.fields
	if len(mpq.fields) > 0 {
		_spec.Unique = mpq.unique != nil && *mpq.unique
	}
	return sqlgraph.CountNodes(ctx, mpq.driver, _spec)
}

func (mpq *MediaPostQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mpq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("storage: check existence: %w", err)
	}
	return n > 0, nil
}

func (mpq *MediaPostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mediapost.Table,
			Columns: mediapost.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mediapost.FieldID,
			},
		},
		From:   mpq.sql,
		Unique: true,
	}
	if unique := mpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediapost.FieldID)
		for i := range fields {
			if fields[i] != mediapost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mpq *MediaPostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mpq.driver.Dialect())
	t1 := builder.Table(mediapost.Table)
	columns := mpq.fields
	if len(columns) == 0 {
		columns = mediapost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mpq.sql != nil {
		selector = mpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mpq.unique != nil && *mpq.unique {
		selector.Distinct()
	}
	for _, p := range mpq.predicates {
		p(selector)
	}
	for _, p := range mpq.order {
		p(selector)
	}
	if offset := mpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MediaPostGroupBy is the group-by builder for MediaPost entities.
type MediaPostGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mpgb *MediaPostGroupBy) Aggregate(fns ...AggregateFunc) *MediaPostGroupBy {
	mpgb.fns = append(mpgb.fns, fns...)
	return mpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mpgb *MediaPostGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mpgb.path(ctx)
	if err != nil {
		return err
	}
	mpgb.sql = query
	return mpgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := mpgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (mpgb *MediaPostGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(mpgb.fields) > 1 {
		return nil, errors.New("storage: MediaPostGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := mpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) StringsX(ctx context.Context) []string {
	v, err := mpgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mpgb *MediaPostGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mpgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = fmt.Errorf("storage: MediaPostGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) StringX(ctx context.Context) string {
	v, err := mpgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (mpgb *MediaPostGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(mpgb.fields) > 1 {
		return nil, errors.New("storage: MediaPostGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := mpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) IntsX(ctx context.Context) []int {
	v, err := mpgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mpgb *MediaPostGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mpgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = fmt.Errorf("storage: MediaPostGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) IntX(ctx context.Context) int {
	v, err := mpgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (mpgb *MediaPostGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(mpgb.fields) > 1 {
		return nil, errors.New("storage: MediaPostGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := mpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := mpgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mpgb *MediaPostGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mpgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = fmt.Errorf("storage: MediaPostGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) Float64X(ctx context.Context) float64 {
	v, err := mpgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (mpgb *MediaPostGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(mpgb.fields) > 1 {
		return nil, errors.New("storage: MediaPostGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := mpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := mpgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mpgb *MediaPostGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mpgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = fmt.Errorf("storage: MediaPostGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mpgb *MediaPostGroupBy) BoolX(ctx context.Context) bool {
	v, err := mpgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mpgb *MediaPostGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mpgb.fields {
		if !mediapost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mpgb *MediaPostGroupBy) sqlQuery() *sql.Selector {
	selector := mpgb.sql.Select()
	aggregation := make([]string, 0, len(mpgb.fns))
	for _, fn := range mpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mpgb.fields)+len(mpgb.fns))
		for _, f := range mpgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mpgb.fields...)...)
}

// MediaPostSelect is the builder for selecting fields of MediaPost entities.
type MediaPostSelect struct {
	*MediaPostQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mps *MediaPostSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mps.prepareQuery(ctx); err != nil {
		return err
	}
	mps.sql = mps.MediaPostQuery.sqlQuery(ctx)
	return mps.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mps *MediaPostSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mps.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mps *MediaPostSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mps.fields) > 1 {
		return nil, errors.New("storage: MediaPostSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mps *MediaPostSelect) StringsX(ctx context.Context) []string {
	v, err := mps.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mps *MediaPostSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mps.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = fmt.Errorf("storage: MediaPostSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mps *MediaPostSelect) StringX(ctx context.Context) string {
	v, err := mps.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mps *MediaPostSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mps.fields) > 1 {
		return nil, errors.New("storage: MediaPostSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mps *MediaPostSelect) IntsX(ctx context.Context) []int {
	v, err := mps.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mps *MediaPostSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mps.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = fmt.Errorf("storage: MediaPostSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mps *MediaPostSelect) IntX(ctx context.Context) int {
	v, err := mps.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mps *MediaPostSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mps.fields) > 1 {
		return nil, errors.New("storage: MediaPostSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mps *MediaPostSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mps.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mps *MediaPostSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mps.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = fmt.Errorf("storage: MediaPostSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mps *MediaPostSelect) Float64X(ctx context.Context) float64 {
	v, err := mps.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mps *MediaPostSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mps.fields) > 1 {
		return nil, errors.New("storage: MediaPostSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mps *MediaPostSelect) BoolsX(ctx context.Context) []bool {
	v, err := mps.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mps *MediaPostSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mps.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mediapost.Label}
	default:
		err = fmt.Errorf("storage: MediaPostSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mps *MediaPostSelect) BoolX(ctx context.Context) bool {
	v, err := mps.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mps *MediaPostSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mps.sql.Query()
	if err := mps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
