// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArticlePostsColumns holds the columns for the "article_posts" table.
	ArticlePostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "title", Type: field.TypeString},
		{Name: "image", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime, Nullable: true},
		{Name: "link", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "source", Type: field.TypeString},
	}
	// ArticlePostsTable holds the schema information for the "article_posts" table.
	ArticlePostsTable = &schema.Table{
		Name:       "article_posts",
		Columns:    ArticlePostsColumns,
		PrimaryKey: []*schema.Column{ArticlePostsColumns[0]},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "article_categories", Type: field.TypeJSON, Nullable: true},
		{Name: "media_categories", Type: field.TypeJSON, Nullable: true},
		{Name: "language", Type: field.TypeString, Default: "fr"},
		{Name: "status", Type: field.TypeBool, Default: true},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// MediaPostsColumns holds the columns for the "media_posts" table.
	MediaPostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "live", Type: field.TypeBool, Default: false},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"youtube", "audio", "video"}},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "logo", Type: field.TypeString},
		{Name: "source", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "image", Type: field.TypeString, Nullable: true},
		{Name: "date", Type: field.TypeTime, Nullable: true},
		{Name: "link", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Nullable: true},
	}
	// MediaPostsTable holds the schema information for the "media_posts" table.
	MediaPostsTable = &schema.Table{
		Name:       "media_posts",
		Columns:    MediaPostsColumns,
		PrimaryKey: []*schema.Column{MediaPostsColumns[0]},
	}
	// SourcesColumns holds the columns for the "sources" table.
	SourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "article_featured_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "article_featured_post_url", Type: field.TypeString, Nullable: true},
		{Name: "article_category_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "article_category_post_url", Type: field.TypeString, Nullable: true},
		{Name: "article_content_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "media_featured_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "media_featured_post_url", Type: field.TypeString, Nullable: true},
		{Name: "media_category_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "media_category_post_url", Type: field.TypeString, Nullable: true},
		{Name: "media_content_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "article_categories", Type: field.TypeJSON, Nullable: true},
		{Name: "media_categories", Type: field.TypeJSON, Nullable: true},
		{Name: "language", Type: field.TypeString, Default: "fr"},
		{Name: "country", Type: field.TypeString, Default: "ci"},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "logo", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
	}
	// SourcesTable holds the schema information for the "sources" table.
	SourcesTable = &schema.Table{
		Name:       "sources",
		Columns:    SourcesColumns,
		PrimaryKey: []*schema.Column{SourcesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArticlePostsTable,
		CategoriesTable,
		MediaPostsTable,
		SourcesTable,
	}
)

func init() {
}
