// Code generated by entc, DO NOT EDIT.

package mediapost

import (
	"fmt"
)

const (
	// Label holds the string label denoting the mediapost type in the database.
	Label = "media_post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLive holds the string denoting the live field in the database.
	FieldLive = "live"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldLogo holds the string denoting the logo field in the database.
	FieldLogo = "logo"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// Table holds the table name of the mediapost in the database.
	Table = "media_posts"
)

// Columns holds all SQL columns for mediapost fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldLive,
	FieldType,
	FieldTitle,
	FieldLogo,
	FieldSource,
	FieldDescription,
	FieldImage,
	FieldDate,
	FieldLink,
	FieldContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
	// DefaultLive holds the default value on creation for the "live" field.
	DefaultLive bool
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeYoutube Type = "youtube"
	TypeAudio   Type = "audio"
	TypeVideo   Type = "video"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeYoutube, TypeAudio, TypeVideo:
		return nil
	default:
		return fmt.Errorf("mediapost: invalid enum value for type field: %q", _type)
	}
}
