// Code generated by entc, DO NOT EDIT.

package articlepost

const (
	// Label holds the string label denoting the articlepost type in the database.
	Label = "article_post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// Table holds the table name of the articlepost in the database.
	Table = "article_posts"
)

// Columns holds all SQL columns for articlepost fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldTitle,
	FieldImage,
	FieldDescription,
	FieldDate,
	FieldLink,
	FieldContent,
	FieldSource,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
)
