// Code generated by entc, DO NOT EDIT.

package newssource

const (
	// Label holds the string label denoting the newssource type in the database.
	Label = "news_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLatestPostURL holds the string denoting the latest_post_url field in the database.
	FieldLatestPostURL = "latest_post_url"
	// FieldLatestPostSelector holds the string denoting the latest_post_selector field in the database.
	FieldLatestPostSelector = "latest_post_selector"
	// FieldCategoryPostURL holds the string denoting the category_post_url field in the database.
	FieldCategoryPostURL = "category_post_url"
	// FieldCategoryPostSelector holds the string denoting the category_post_selector field in the database.
	FieldCategoryPostSelector = "category_post_selector"
	// FieldArticleSelector holds the string denoting the article_selector field in the database.
	FieldArticleSelector = "article_selector"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCategories holds the string denoting the categories field in the database.
	FieldCategories = "categories"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// Table holds the table name of the newssource in the database.
	Table = "news_sources"
)

// Columns holds all SQL columns for newssource fields.
var Columns = []string{
	FieldID,
	FieldLatestPostURL,
	FieldLatestPostSelector,
	FieldCategoryPostURL,
	FieldCategoryPostSelector,
	FieldArticleSelector,
	FieldLanguage,
	FieldCountry,
	FieldStatus,
	FieldName,
	FieldCategories,
	FieldURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
)
