// Code generated by entc, DO NOT EDIT.

package newscategories

const (
	// Label holds the string label denoting the newscategories type in the database.
	Label = "news_categories"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldTvCategories holds the string denoting the tv_categories field in the database.
	FieldTvCategories = "tv_categories"
	// FieldArticleCategories holds the string denoting the article_categories field in the database.
	FieldArticleCategories = "article_categories"
	// Table holds the table name of the newscategories in the database.
	Table = "news_categories"
)

// Columns holds all SQL columns for newscategories fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldLanguage,
	FieldTvCategories,
	FieldArticleCategories,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
)
