// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NewsSourcesColumns holds the columns for the "news_sources" table.
	NewsSourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "latest_post_url", Type: field.TypeString, Nullable: true},
		{Name: "latest_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "category_post_url", Type: field.TypeString, Nullable: true},
		{Name: "category_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "article_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "language", Type: field.TypeString, Default: "fr"},
		{Name: "country", Type: field.TypeString, Default: "ci"},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "logo", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "categories", Type: field.TypeJSON},
		{Name: "url", Type: field.TypeString},
	}
	// NewsSourcesTable holds the schema information for the "news_sources" table.
	NewsSourcesTable = &schema.Table{
		Name:       "news_sources",
		Columns:    NewsSourcesColumns,
		PrimaryKey: []*schema.Column{NewsSourcesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NewsSourcesTable,
	}
)

func init() {
}
