// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NewsArticleSourcesColumns holds the columns for the "news_article_sources" table.
	NewsArticleSourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "latest_post_url", Type: field.TypeString, Nullable: true},
		{Name: "latest_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "category_post_url", Type: field.TypeString, Nullable: true},
		{Name: "category_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "article_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "categories", Type: field.TypeJSON},
		{Name: "language", Type: field.TypeString, Default: "fr"},
		{Name: "country", Type: field.TypeString, Default: "ci"},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "logo", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
	}
	// NewsArticleSourcesTable holds the schema information for the "news_article_sources" table.
	NewsArticleSourcesTable = &schema.Table{
		Name:       "news_article_sources",
		Columns:    NewsArticleSourcesColumns,
		PrimaryKey: []*schema.Column{NewsArticleSourcesColumns[0]},
	}
	// NewsCategoriesColumns holds the columns for the "news_categories" table.
	NewsCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "language", Type: field.TypeString, Default: "fr"},
		{Name: "tv_categories", Type: field.TypeJSON},
		{Name: "article_categories", Type: field.TypeJSON},
	}
	// NewsCategoriesTable holds the schema information for the "news_categories" table.
	NewsCategoriesTable = &schema.Table{
		Name:       "news_categories",
		Columns:    NewsCategoriesColumns,
		PrimaryKey: []*schema.Column{NewsCategoriesColumns[0]},
	}
	// NewsTvSourcesColumns holds the columns for the "news_tv_sources" table.
	NewsTvSourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "logo", Type: field.TypeString},
		{Name: "video", Type: field.TypeString},
		{Name: "live", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "country", Type: field.TypeString, Default: "ci"},
		{Name: "description", Type: field.TypeString},
		{Name: "language", Type: field.TypeString, Default: "fr"},
		{Name: "source", Type: field.TypeString, Unique: true},
		{Name: "categories", Type: field.TypeJSON, Nullable: true},
	}
	// NewsTvSourcesTable holds the schema information for the "news_tv_sources" table.
	NewsTvSourcesTable = &schema.Table{
		Name:       "news_tv_sources",
		Columns:    NewsTvSourcesColumns,
		PrimaryKey: []*schema.Column{NewsTvSourcesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NewsArticleSourcesTable,
		NewsCategoriesTable,
		NewsTvSourcesTable,
	}
)

func init() {
}
