// Code generated by entc, DO NOT EDIT.

package store

import (
	"encoding/json"
	"fmt"
	"news/internal/store/newsarticlesource"
	"news/internal/store/schema"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// NewsArticleSource is the model entity for the NewsArticleSource schema.
type NewsArticleSource struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// LatestPostURL holds the value of the "latest_post_url" field.
	LatestPostURL *string `json:"latest_post_url,omitempty"`
	// LatestPostSelector holds the value of the "latest_post_selector" field.
	LatestPostSelector *schema.NewsPostSelector `json:"latest_post_selector,omitempty"`
	// CategoryPostURL holds the value of the "category_post_url" field.
	CategoryPostURL *string `json:"category_post_url,omitempty"`
	// CategoryPostSelector holds the value of the "category_post_selector" field.
	CategoryPostSelector *schema.NewsPostSelector `json:"category_post_selector,omitempty"`
	// ArticleSelector holds the value of the "article_selector" field.
	ArticleSelector *schema.NewsArticleSelector `json:"article_selector,omitempty"`
	// Categories holds the value of the "categories" field.
	Categories map[string]string `json:"categories,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// Status holds the value of the "status" field.
	Status bool `json:"status,omitempty"`
	// Logo holds the value of the "logo" field.
	Logo string `json:"logo,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NewsArticleSource) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case newsarticlesource.FieldLatestPostSelector, newsarticlesource.FieldCategoryPostSelector, newsarticlesource.FieldArticleSelector, newsarticlesource.FieldCategories:
			values[i] = new([]byte)
		case newsarticlesource.FieldStatus:
			values[i] = new(sql.NullBool)
		case newsarticlesource.FieldID:
			values[i] = new(sql.NullInt64)
		case newsarticlesource.FieldLatestPostURL, newsarticlesource.FieldCategoryPostURL, newsarticlesource.FieldLanguage, newsarticlesource.FieldCountry, newsarticlesource.FieldLogo, newsarticlesource.FieldName, newsarticlesource.FieldURL:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type NewsArticleSource", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NewsArticleSource fields.
func (nas *NewsArticleSource) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case newsarticlesource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			nas.ID = int(value.Int64)
		case newsarticlesource.FieldLatestPostURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field latest_post_url", values[i])
			} else if value.Valid {
				nas.LatestPostURL = new(string)
				*nas.LatestPostURL = value.String
			}
		case newsarticlesource.FieldLatestPostSelector:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field latest_post_selector", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &nas.LatestPostSelector); err != nil {
					return fmt.Errorf("unmarshal field latest_post_selector: %w", err)
				}
			}
		case newsarticlesource.FieldCategoryPostURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_post_url", values[i])
			} else if value.Valid {
				nas.CategoryPostURL = new(string)
				*nas.CategoryPostURL = value.String
			}
		case newsarticlesource.FieldCategoryPostSelector:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field category_post_selector", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &nas.CategoryPostSelector); err != nil {
					return fmt.Errorf("unmarshal field category_post_selector: %w", err)
				}
			}
		case newsarticlesource.FieldArticleSelector:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field article_selector", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &nas.ArticleSelector); err != nil {
					return fmt.Errorf("unmarshal field article_selector: %w", err)
				}
			}
		case newsarticlesource.FieldCategories:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field categories", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &nas.Categories); err != nil {
					return fmt.Errorf("unmarshal field categories: %w", err)
				}
			}
		case newsarticlesource.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				nas.Language = value.String
			}
		case newsarticlesource.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				nas.Country = value.String
			}
		case newsarticlesource.FieldStatus:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				nas.Status = value.Bool
			}
		case newsarticlesource.FieldLogo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo", values[i])
			} else if value.Valid {
				nas.Logo = value.String
			}
		case newsarticlesource.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				nas.Name = value.String
			}
		case newsarticlesource.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				nas.URL = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this NewsArticleSource.
// Note that you need to call NewsArticleSource.Unwrap() before calling this method if this NewsArticleSource
// was returned from a transaction, and the transaction was committed or rolled back.
func (nas *NewsArticleSource) Update() *NewsArticleSourceUpdateOne {
	return (&NewsArticleSourceClient{config: nas.config}).UpdateOne(nas)
}

// Unwrap unwraps the NewsArticleSource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (nas *NewsArticleSource) Unwrap() *NewsArticleSource {
	tx, ok := nas.config.driver.(*txDriver)
	if !ok {
		panic("store: NewsArticleSource is not a transactional entity")
	}
	nas.config.driver = tx.drv
	return nas
}

// String implements the fmt.Stringer.
func (nas *NewsArticleSource) String() string {
	var builder strings.Builder
	builder.WriteString("NewsArticleSource(")
	builder.WriteString(fmt.Sprintf("id=%v", nas.ID))
	if v := nas.LatestPostURL; v != nil {
		builder.WriteString(", latest_post_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", latest_post_selector=")
	builder.WriteString(fmt.Sprintf("%v", nas.LatestPostSelector))
	if v := nas.CategoryPostURL; v != nil {
		builder.WriteString(", category_post_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", category_post_selector=")
	builder.WriteString(fmt.Sprintf("%v", nas.CategoryPostSelector))
	builder.WriteString(", article_selector=")
	builder.WriteString(fmt.Sprintf("%v", nas.ArticleSelector))
	builder.WriteString(", categories=")
	builder.WriteString(fmt.Sprintf("%v", nas.Categories))
	builder.WriteString(", language=")
	builder.WriteString(nas.Language)
	builder.WriteString(", country=")
	builder.WriteString(nas.Country)
	builder.WriteString(", status=")
	builder.WriteString(fmt.Sprintf("%v", nas.Status))
	builder.WriteString(", logo=")
	builder.WriteString(nas.Logo)
	builder.WriteString(", name=")
	builder.WriteString(nas.Name)
	builder.WriteString(", url=")
	builder.WriteString(nas.URL)
	builder.WriteByte(')')
	return builder.String()
}

// NewsArticleSources is a parsable slice of NewsArticleSource.
type NewsArticleSources []*NewsArticleSource

func (nas NewsArticleSources) config(cfg config) {
	for _i := range nas {
		nas[_i].config = cfg
	}
}
