// Code generated by entc, DO NOT EDIT.

package store

import (
	"context"
	"fmt"
	"news/internal/store/newsarticlesource"
	"news/internal/store/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NewsArticleSourceDelete is the builder for deleting a NewsArticleSource entity.
type NewsArticleSourceDelete struct {
	config
	hooks    []Hook
	mutation *NewsArticleSourceMutation
}

// Where appends a list predicates to the NewsArticleSourceDelete builder.
func (nasd *NewsArticleSourceDelete) Where(ps ...predicate.NewsArticleSource) *NewsArticleSourceDelete {
	nasd.mutation.Where(ps...)
	return nasd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nasd *NewsArticleSourceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(nasd.hooks) == 0 {
		affected, err = nasd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NewsArticleSourceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nasd.mutation = mutation
			affected, err = nasd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nasd.hooks) - 1; i >= 0; i-- {
			if nasd.hooks[i] == nil {
				return 0, fmt.Errorf("store: uninitialized hook (forgotten import store/runtime?)")
			}
			mut = nasd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nasd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (nasd *NewsArticleSourceDelete) ExecX(ctx context.Context) int {
	n, err := nasd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nasd *NewsArticleSourceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: newsarticlesource.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: newsarticlesource.FieldID,
			},
		},
	}
	if ps := nasd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, nasd.driver, _spec)
}

// NewsArticleSourceDeleteOne is the builder for deleting a single NewsArticleSource entity.
type NewsArticleSourceDeleteOne struct {
	nasd *NewsArticleSourceDelete
}

// Exec executes the deletion query.
func (nasdo *NewsArticleSourceDeleteOne) Exec(ctx context.Context) error {
	n, err := nasdo.nasd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{newsarticlesource.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nasdo *NewsArticleSourceDeleteOne) ExecX(ctx context.Context) {
	nasdo.nasd.ExecX(ctx)
}
