// Code generated by entc, DO NOT EDIT.

package store

import (
	"context"
	"fmt"
	"news/internal/store/newstvsource"
	"news/internal/store/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NewsTvSourceDelete is the builder for deleting a NewsTvSource entity.
type NewsTvSourceDelete struct {
	config
	hooks    []Hook
	mutation *NewsTvSourceMutation
}

// Where appends a list predicates to the NewsTvSourceDelete builder.
func (ntsd *NewsTvSourceDelete) Where(ps ...predicate.NewsTvSource) *NewsTvSourceDelete {
	ntsd.mutation.Where(ps...)
	return ntsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ntsd *NewsTvSourceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ntsd.hooks) == 0 {
		affected, err = ntsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NewsTvSourceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ntsd.mutation = mutation
			affected, err = ntsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ntsd.hooks) - 1; i >= 0; i-- {
			if ntsd.hooks[i] == nil {
				return 0, fmt.Errorf("store: uninitialized hook (forgotten import store/runtime?)")
			}
			mut = ntsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ntsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntsd *NewsTvSourceDelete) ExecX(ctx context.Context) int {
	n, err := ntsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ntsd *NewsTvSourceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: newstvsource.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: newstvsource.FieldID,
			},
		},
	}
	if ps := ntsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ntsd.driver, _spec)
}

// NewsTvSourceDeleteOne is the builder for deleting a single NewsTvSource entity.
type NewsTvSourceDeleteOne struct {
	ntsd *NewsTvSourceDelete
}

// Exec executes the deletion query.
func (ntsdo *NewsTvSourceDeleteOne) Exec(ctx context.Context) error {
	n, err := ntsdo.ntsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{newstvsource.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ntsdo *NewsTvSourceDeleteOne) ExecX(ctx context.Context) {
	ntsdo.ntsd.ExecX(ctx)
}
