// Code generated by entc, DO NOT EDIT.

package store

import (
	"context"
	"fmt"
	"news/internal/store/newscategories"
	"news/internal/store/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NewsCategoriesDelete is the builder for deleting a NewsCategories entity.
type NewsCategoriesDelete struct {
	config
	hooks    []Hook
	mutation *NewsCategoriesMutation
}

// Where appends a list predicates to the NewsCategoriesDelete builder.
func (ncd *NewsCategoriesDelete) Where(ps ...predicate.NewsCategories) *NewsCategoriesDelete {
	ncd.mutation.Where(ps...)
	return ncd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ncd *NewsCategoriesDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ncd.hooks) == 0 {
		affected, err = ncd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NewsCategoriesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ncd.mutation = mutation
			affected, err = ncd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ncd.hooks) - 1; i >= 0; i-- {
			if ncd.hooks[i] == nil {
				return 0, fmt.Errorf("store: uninitialized hook (forgotten import store/runtime?)")
			}
			mut = ncd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ncd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncd *NewsCategoriesDelete) ExecX(ctx context.Context) int {
	n, err := ncd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ncd *NewsCategoriesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: newscategories.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: newscategories.FieldID,
			},
		},
	}
	if ps := ncd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ncd.driver, _spec)
}

// NewsCategoriesDeleteOne is the builder for deleting a single NewsCategories entity.
type NewsCategoriesDeleteOne struct {
	ncd *NewsCategoriesDelete
}

// Exec executes the deletion query.
func (ncdo *NewsCategoriesDeleteOne) Exec(ctx context.Context) error {
	n, err := ncdo.ncd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{newscategories.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ncdo *NewsCategoriesDeleteOne) ExecX(ctx context.Context) {
	ncdo.ncd.ExecX(ctx)
}
