// Code generated by entc, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"math"
	"news/internal/store/newssource"
	"news/internal/store/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NewsSourceQuery is the builder for querying NewsSource entities.
type NewsSourceQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.NewsSource
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NewsSourceQuery builder.
func (nsq *NewsSourceQuery) Where(ps ...predicate.NewsSource) *NewsSourceQuery {
	nsq.predicates = append(nsq.predicates, ps...)
	return nsq
}

// Limit adds a limit step to the query.
func (nsq *NewsSourceQuery) Limit(limit int) *NewsSourceQuery {
	nsq.limit = &limit
	return nsq
}

// Offset adds an offset step to the query.
func (nsq *NewsSourceQuery) Offset(offset int) *NewsSourceQuery {
	nsq.offset = &offset
	return nsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nsq *NewsSourceQuery) Unique(unique bool) *NewsSourceQuery {
	nsq.unique = &unique
	return nsq
}

// Order adds an order step to the query.
func (nsq *NewsSourceQuery) Order(o ...OrderFunc) *NewsSourceQuery {
	nsq.order = append(nsq.order, o...)
	return nsq
}

// First returns the first NewsSource entity from the query.
// Returns a *NotFoundError when no NewsSource was found.
func (nsq *NewsSourceQuery) First(ctx context.Context) (*NewsSource, error) {
	nodes, err := nsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{newssource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nsq *NewsSourceQuery) FirstX(ctx context.Context) *NewsSource {
	node, err := nsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NewsSource ID from the query.
// Returns a *NotFoundError when no NewsSource ID was found.
func (nsq *NewsSourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{newssource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nsq *NewsSourceQuery) FirstIDX(ctx context.Context) int {
	id, err := nsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NewsSource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NewsSource entity is found.
// Returns a *NotFoundError when no NewsSource entities are found.
func (nsq *NewsSourceQuery) Only(ctx context.Context) (*NewsSource, error) {
	nodes, err := nsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{newssource.Label}
	default:
		return nil, &NotSingularError{newssource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nsq *NewsSourceQuery) OnlyX(ctx context.Context) *NewsSource {
	node, err := nsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NewsSource ID in the query.
// Returns a *NotSingularError when more than one NewsSource ID is found.
// Returns a *NotFoundError when no entities are found.
func (nsq *NewsSourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = &NotSingularError{newssource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nsq *NewsSourceQuery) OnlyIDX(ctx context.Context) int {
	id, err := nsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NewsSources.
func (nsq *NewsSourceQuery) All(ctx context.Context) ([]*NewsSource, error) {
	if err := nsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return nsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (nsq *NewsSourceQuery) AllX(ctx context.Context) []*NewsSource {
	nodes, err := nsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NewsSource IDs.
func (nsq *NewsSourceQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := nsq.Select(newssource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nsq *NewsSourceQuery) IDsX(ctx context.Context) []int {
	ids, err := nsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nsq *NewsSourceQuery) Count(ctx context.Context) (int, error) {
	if err := nsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return nsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (nsq *NewsSourceQuery) CountX(ctx context.Context) int {
	count, err := nsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nsq *NewsSourceQuery) Exist(ctx context.Context) (bool, error) {
	if err := nsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return nsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (nsq *NewsSourceQuery) ExistX(ctx context.Context) bool {
	exist, err := nsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NewsSourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nsq *NewsSourceQuery) Clone() *NewsSourceQuery {
	if nsq == nil {
		return nil
	}
	return &NewsSourceQuery{
		config:     nsq.config,
		limit:      nsq.limit,
		offset:     nsq.offset,
		order:      append([]OrderFunc{}, nsq.order...),
		predicates: append([]predicate.NewsSource{}, nsq.predicates...),
		// clone intermediate query.
		sql:    nsq.sql.Clone(),
		path:   nsq.path,
		unique: nsq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LatestPostURL string `json:"latest_post_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NewsSource.Query().
//		GroupBy(newssource.FieldLatestPostURL).
//		Aggregate(store.Count()).
//		Scan(ctx, &v)
//
func (nsq *NewsSourceQuery) GroupBy(field string, fields ...string) *NewsSourceGroupBy {
	group := &NewsSourceGroupBy{config: nsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := nsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return nsq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LatestPostURL string `json:"latest_post_url,omitempty"`
//	}
//
//	client.NewsSource.Query().
//		Select(newssource.FieldLatestPostURL).
//		Scan(ctx, &v)
//
func (nsq *NewsSourceQuery) Select(fields ...string) *NewsSourceSelect {
	nsq.fields = append(nsq.fields, fields...)
	return &NewsSourceSelect{NewsSourceQuery: nsq}
}

func (nsq *NewsSourceQuery) prepareQuery(ctx context.Context) error {
	for _, f := range nsq.fields {
		if !newssource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("store: invalid field %q for query", f)}
		}
	}
	if nsq.path != nil {
		prev, err := nsq.path(ctx)
		if err != nil {
			return err
		}
		nsq.sql = prev
	}
	return nil
}

func (nsq *NewsSourceQuery) sqlAll(ctx context.Context) ([]*NewsSource, error) {
	var (
		nodes = []*NewsSource{}
		_spec = nsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &NewsSource{config: nsq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("store: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, nsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (nsq *NewsSourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nsq.querySpec()
	_spec.Node.Columns = nsq.fields
	if len(nsq.fields) > 0 {
		_spec.Unique = nsq.unique != nil && *nsq.unique
	}
	return sqlgraph.CountNodes(ctx, nsq.driver, _spec)
}

func (nsq *NewsSourceQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := nsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("store: check existence: %w", err)
	}
	return n > 0, nil
}

func (nsq *NewsSourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   newssource.Table,
			Columns: newssource.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: newssource.FieldID,
			},
		},
		From:   nsq.sql,
		Unique: true,
	}
	if unique := nsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := nsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, newssource.FieldID)
		for i := range fields {
			if fields[i] != newssource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nsq *NewsSourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nsq.driver.Dialect())
	t1 := builder.Table(newssource.Table)
	columns := nsq.fields
	if len(columns) == 0 {
		columns = newssource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nsq.sql != nil {
		selector = nsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nsq.unique != nil && *nsq.unique {
		selector.Distinct()
	}
	for _, p := range nsq.predicates {
		p(selector)
	}
	for _, p := range nsq.order {
		p(selector)
	}
	if offset := nsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NewsSourceGroupBy is the group-by builder for NewsSource entities.
type NewsSourceGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nsgb *NewsSourceGroupBy) Aggregate(fns ...AggregateFunc) *NewsSourceGroupBy {
	nsgb.fns = append(nsgb.fns, fns...)
	return nsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (nsgb *NewsSourceGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := nsgb.path(ctx)
	if err != nil {
		return err
	}
	nsgb.sql = query
	return nsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := nsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (nsgb *NewsSourceGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(nsgb.fields) > 1 {
		return nil, errors.New("store: NewsSourceGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := nsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) StringsX(ctx context.Context) []string {
	v, err := nsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nsgb *NewsSourceGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = fmt.Errorf("store: NewsSourceGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) StringX(ctx context.Context) string {
	v, err := nsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (nsgb *NewsSourceGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(nsgb.fields) > 1 {
		return nil, errors.New("store: NewsSourceGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := nsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) IntsX(ctx context.Context) []int {
	v, err := nsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nsgb *NewsSourceGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = fmt.Errorf("store: NewsSourceGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) IntX(ctx context.Context) int {
	v, err := nsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (nsgb *NewsSourceGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(nsgb.fields) > 1 {
		return nil, errors.New("store: NewsSourceGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := nsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := nsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nsgb *NewsSourceGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = fmt.Errorf("store: NewsSourceGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) Float64X(ctx context.Context) float64 {
	v, err := nsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (nsgb *NewsSourceGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(nsgb.fields) > 1 {
		return nil, errors.New("store: NewsSourceGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := nsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := nsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nsgb *NewsSourceGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = fmt.Errorf("store: NewsSourceGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nsgb *NewsSourceGroupBy) BoolX(ctx context.Context) bool {
	v, err := nsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nsgb *NewsSourceGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range nsgb.fields {
		if !newssource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := nsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (nsgb *NewsSourceGroupBy) sqlQuery() *sql.Selector {
	selector := nsgb.sql.Select()
	aggregation := make([]string, 0, len(nsgb.fns))
	for _, fn := range nsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(nsgb.fields)+len(nsgb.fns))
		for _, f := range nsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(nsgb.fields...)...)
}

// NewsSourceSelect is the builder for selecting fields of NewsSource entities.
type NewsSourceSelect struct {
	*NewsSourceQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (nss *NewsSourceSelect) Scan(ctx context.Context, v interface{}) error {
	if err := nss.prepareQuery(ctx); err != nil {
		return err
	}
	nss.sql = nss.NewsSourceQuery.sqlQuery(ctx)
	return nss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nss *NewsSourceSelect) ScanX(ctx context.Context, v interface{}) {
	if err := nss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (nss *NewsSourceSelect) Strings(ctx context.Context) ([]string, error) {
	if len(nss.fields) > 1 {
		return nil, errors.New("store: NewsSourceSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := nss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nss *NewsSourceSelect) StringsX(ctx context.Context) []string {
	v, err := nss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (nss *NewsSourceSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = fmt.Errorf("store: NewsSourceSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nss *NewsSourceSelect) StringX(ctx context.Context) string {
	v, err := nss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (nss *NewsSourceSelect) Ints(ctx context.Context) ([]int, error) {
	if len(nss.fields) > 1 {
		return nil, errors.New("store: NewsSourceSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := nss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nss *NewsSourceSelect) IntsX(ctx context.Context) []int {
	v, err := nss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (nss *NewsSourceSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = fmt.Errorf("store: NewsSourceSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nss *NewsSourceSelect) IntX(ctx context.Context) int {
	v, err := nss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (nss *NewsSourceSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(nss.fields) > 1 {
		return nil, errors.New("store: NewsSourceSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := nss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nss *NewsSourceSelect) Float64sX(ctx context.Context) []float64 {
	v, err := nss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (nss *NewsSourceSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = fmt.Errorf("store: NewsSourceSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nss *NewsSourceSelect) Float64X(ctx context.Context) float64 {
	v, err := nss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (nss *NewsSourceSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(nss.fields) > 1 {
		return nil, errors.New("store: NewsSourceSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := nss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nss *NewsSourceSelect) BoolsX(ctx context.Context) []bool {
	v, err := nss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (nss *NewsSourceSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{newssource.Label}
	default:
		err = fmt.Errorf("store: NewsSourceSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nss *NewsSourceSelect) BoolX(ctx context.Context) bool {
	v, err := nss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nss *NewsSourceSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := nss.sql.Query()
	if err := nss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
