// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// NewsSource is the predicate function for newssource builders.
type NewsSource func(*sql.Selector)
