// Code generated by entc, DO NOT EDIT.

package categories

const (
	// Label holds the string label denoting the categories type in the database.
	Label = "categories"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldArticleCategories holds the string denoting the article_categories field in the database.
	FieldArticleCategories = "article_categories"
	// FieldMediaCategories holds the string denoting the media_categories field in the database.
	FieldMediaCategories = "media_categories"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the categories in the database.
	Table = "categories"
)

// Columns holds all SQL columns for categories fields.
var Columns = []string{
	FieldID,
	FieldArticleCategories,
	FieldMediaCategories,
	FieldLanguage,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
)
