// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ArticlePost is the predicate function for articlepost builders.
type ArticlePost func(*sql.Selector)

// Categories is the predicate function for categories builders.
type Categories func(*sql.Selector)

// MediaPost is the predicate function for mediapost builders.
type MediaPost func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)
