// Code generated by entc, DO NOT EDIT.

package newstvsource

const (
	// Label holds the string label denoting the newstvsource type in the database.
	Label = "news_tv_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLogo holds the string denoting the logo field in the database.
	FieldLogo = "logo"
	// FieldVideo holds the string denoting the video field in the database.
	FieldVideo = "video"
	// FieldLive holds the string denoting the live field in the database.
	FieldLive = "live"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCategories holds the string denoting the categories field in the database.
	FieldCategories = "categories"
	// Table holds the table name of the newstvsource in the database.
	Table = "news_tv_sources"
)

// Columns holds all SQL columns for newstvsource fields.
var Columns = []string{
	FieldID,
	FieldLogo,
	FieldVideo,
	FieldLive,
	FieldStatus,
	FieldCountry,
	FieldDescription,
	FieldLanguage,
	FieldSource,
	FieldCategories,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LogoValidator is a validator for the "logo" field. It is called by the builders before save.
	LogoValidator func(string) error
	// VideoValidator is a validator for the "video" field. It is called by the builders before save.
	VideoValidator func(string) error
	// DefaultLive holds the default value on creation for the "live" field.
	DefaultLive bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
)
